var SETTINGSSCHEMA = {
    name: String,
    email: String,
    password: String,
    ticket: String,
    phonecode: String,
    logo: String,
    role: String,
    seo: {},
    site: {},
    previleges: [],
    device: String,
    time: String,
    ip: String,
    city: String,
    region: String,
    country: String,
    countrycode: String,
    latitude: String,
    longitude: String,
    postal: String,
    currencyname: String,
    currencycode: String,
    currencysymbol: String,
    dateformate: String,
    timeformat: String,
    username: String,
    adminpassword: String,
    image: String,
    status: Boolean,
};

module.exports = SETTINGSSCHEMA;